version: "3.8"

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: cv-be-test-db
    environment:
      POSTGRES_DB: cv_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    tmpfs:
      - /tmp
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d cv_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_postgres_data:
    driver: local
